//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConAnecoop.AnecoopLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.anecoop.com/", ConfigurationName="AnecoopLogin.LoginSoap")]
    public interface LoginSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.anecoop.com/CheckLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConAnecoop.AnecoopLogin.ServiceTicket CheckLogin(string Usuario, string Empresa, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.anecoop.com/CheckLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ConAnecoop.AnecoopLogin.ServiceTicket> CheckLoginAsync(string Usuario, string Empresa, string Password);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.anecoop.com/")]
    public partial class ServiceTicket : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isAuthenticatedField;
        
        private string sessionKeyField;
        
        private System.DateTime expirationField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsAuthenticated {
            get {
                return this.isAuthenticatedField;
            }
            set {
                this.isAuthenticatedField = value;
                this.RaisePropertyChanged("IsAuthenticated");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SessionKey {
            get {
                return this.sessionKeyField;
            }
            set {
                this.sessionKeyField = value;
                this.RaisePropertyChanged("SessionKey");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
                this.RaisePropertyChanged("Expiration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginSoapChannel : ConAnecoop.AnecoopLogin.LoginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSoapClient : System.ServiceModel.ClientBase<ConAnecoop.AnecoopLogin.LoginSoap>, ConAnecoop.AnecoopLogin.LoginSoap {
        
        public LoginSoapClient() {
        }
        
        public LoginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConAnecoop.AnecoopLogin.ServiceTicket CheckLogin(string Usuario, string Empresa, string Password) {
            return base.Channel.CheckLogin(Usuario, Empresa, Password);
        }
        
        public System.Threading.Tasks.Task<ConAnecoop.AnecoopLogin.ServiceTicket> CheckLoginAsync(string Usuario, string Empresa, string Password) {
            return base.Channel.CheckLoginAsync(Usuario, Empresa, Password);
        }
    }
}
