//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConAnecoop.AnecoopConsultaExpediente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AnecoopConsultaExpediente.JSVConsultaExpedienteSoap")]
    public interface JSVConsultaExpedienteSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://tempuri.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargaPedidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResponse DescargaPedidos(ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DescargaPedidos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResponse> DescargaPedidosAsync(ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DescargaPedidosResultExpediente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eXPEDIENTE_IDField;
        
        private string pdls_idField;
        
        private string lINEA_EXPEDIENTEField;
        
        private string cODIGO_CAMPANYAField;
        
        private string pERIODOField;
        
        private decimal cODIGO_COOPERATIVA_GESTORAField;
        
        private string nOMBRE_GESTORAField;
        
        private decimal cODIGO_COOPERATIVA_CARGAField;
        
        private string nOMBRE_CARGAField;
        
        private string pTO_CARGAField;
        
        private string nOMBRE_PTO_CARGAField;
        
        private string nUMERO_SALIDA_COOPERATIVAField;
        
        private string n_LINEA_SALIDA_COOPERATIVAField;
        
        private decimal n_PEDIDO_ANECOOPField;
        
        private bool n_PEDIDO_ANECOOPFieldSpecified;
        
        private decimal n_PEDIDOField;
        
        private bool n_PEDIDOFieldSpecified;
        
        private decimal n_LINEAField;
        
        private bool n_LINEAFieldSpecified;
        
        private string tIPO_EXPEDIENTEField;
        
        private string eSTADO_COOP_EXPEDIENTEField;
        
        private string eXPEDIENTE_REENVIADOField;
        
        private string cODIGO_DELEGACIONField;
        
        private string nOMBRE_DELEGACIONField;
        
        private string cODIGO_AREAField;
        
        private string nOMBRE_AREAField;
        
        private System.DateTime fECHA_SALIDAField;
        
        private bool fECHA_SALIDAFieldSpecified;
        
        private string mATRICULAField;
        
        private string tIPO_VEHICULOField;
        
        private string cATEGORIAField;
        
        private string nOMBRE_CATEGORIAField;
        
        private string cODIGO_CONFECCIONField;
        
        private string nOMBRE_CONFECCIONField;
        
        private string cODIGO_UVENTAField;
        
        private string nOMBRE_UVENTAField;
        
        private string cODIGO_ETRANSPORTEField;
        
        private string nOMBRE_ETRANSPORTEField;
        
        private string cODIGO_MODELOField;
        
        private string nOMBRE_MODELOField;
        
        private string cODIGO_MATERIALField;
        
        private string nOMBRE_MATERIALField;
        
        private string cODIGO_MARCAField;
        
        private string nOMBRE_MARCAField;
        
        private string cODIGO_VARIEDADField;
        
        private string nOMBRE_VARIEDADField;
        
        private string cODIGO_ARTICULOField;
        
        private string nOMBRE_ARTICULOField;
        
        private string cODIGO_CLIENTEField;
        
        private string nOMBRECLIENTEField;
        
        private string cODIGO_PAISField;
        
        private string cODIGO_DIVISA_CLIENTEField;
        
        private string cODIGO_PRODUCTOField;
        
        private string nOMBRE_PRODUCTOField;
        
        private string cODIGO_CALIBREField;
        
        private string nOMBRE_CALIBREField;
        
        private decimal nPALETField;
        
        private string tIPO_PALETField;
        
        private string nOMBRE_TIPO_PALETField;
        
        private decimal nCAJASField;
        
        private decimal pESO_NETOField;
        
        private decimal pRECIO_COMERCIALField;
        
        private string cODIGO_DIVISAField;
        
        private string lIQUIDADO_SONField;
        
        private string eSTADO_COOP_LIQUIDACIONField;
        
        private string lIQUIDACION_AGRUPADA_SONField;
        
        private string cODIGO_GRUPO_LIQUIDACIONField;
        
        private decimal nUM_LIQField;
        
        private bool nUM_LIQFieldSpecified;
        
        private string fRA_LIQField;
        
        private string fRA_LIQ_COMPLEMENTAField;
        
        private string cARTA_LIQField;
        
        private string rEGISTRO_LIQField;
        
        private decimal iMPORTE_LIQField;
        
        private bool iMPORTE_LIQFieldSpecified;
        
        private decimal iMPORTE_IVA_LIQField;
        
        private bool iMPORTE_IVA_LIQFieldSpecified;
        
        private string tIPO_IVA_LIQField;
        
        private System.DateTime fECHA_LIQField;
        
        private bool fECHA_LIQFieldSpecified;
        
        private System.DateTime fECHA_CAMBIO_LIQField;
        
        private bool fECHA_CAMBIO_LIQFieldSpecified;
        
        private decimal cAMBIO_LIQField;
        
        private bool cAMBIO_LIQFieldSpecified;
        
        private System.DateTime fECHA_SC_LIQField;
        
        private bool fECHA_SC_LIQFieldSpecified;
        
        private decimal pORCENT_IVA_LIQField;
        
        private bool pORCENT_IVA_LIQFieldSpecified;
        
        private decimal iMPORTE2_IVA_LIQField;
        
        private bool iMPORTE2_IVA_LIQFieldSpecified;
        
        private string cOBRADO_SONField;
        
        private string pAGADO_SONField;
        
        private decimal vALOR_MERCANCIAField;
        
        private bool vALOR_MERCANCIAFieldSpecified;
        
        private decimal vALOR_CONFECCIONField;
        
        private bool vALOR_CONFECCIONFieldSpecified;
        
        private decimal nUMERO_SALIDA_ANECOOPField;
        
        private bool nUMERO_SALIDA_ANECOOPFieldSpecified;
        
        private string sALIDALINEAIDField;
        
        private string cODIGO_TIPO_ARTICULOField;
        
        private string eAN13Field;
        
        private string uNIDAD_PESOField;
        
        private DescargaPedidosResultExpedienteEXPEDIENTE_PAGO[] eXPEDIENTE_PAGOField;
        
        private DescargaPedidosResultExpedienteEXPEDIENTE_COBRO[] eXPEDIENTE_COBROField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EXPEDIENTE_ID {
            get {
                return this.eXPEDIENTE_IDField;
            }
            set {
                this.eXPEDIENTE_IDField = value;
                this.RaisePropertyChanged("EXPEDIENTE_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pdls_id {
            get {
                return this.pdls_idField;
            }
            set {
                this.pdls_idField = value;
                this.RaisePropertyChanged("pdls_id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LINEA_EXPEDIENTE {
            get {
                return this.lINEA_EXPEDIENTEField;
            }
            set {
                this.lINEA_EXPEDIENTEField = value;
                this.RaisePropertyChanged("LINEA_EXPEDIENTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CODIGO_CAMPANYA {
            get {
                return this.cODIGO_CAMPANYAField;
            }
            set {
                this.cODIGO_CAMPANYAField = value;
                this.RaisePropertyChanged("CODIGO_CAMPANYA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PERIODO {
            get {
                return this.pERIODOField;
            }
            set {
                this.pERIODOField = value;
                this.RaisePropertyChanged("PERIODO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal CODIGO_COOPERATIVA_GESTORA {
            get {
                return this.cODIGO_COOPERATIVA_GESTORAField;
            }
            set {
                this.cODIGO_COOPERATIVA_GESTORAField = value;
                this.RaisePropertyChanged("CODIGO_COOPERATIVA_GESTORA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NOMBRE_GESTORA {
            get {
                return this.nOMBRE_GESTORAField;
            }
            set {
                this.nOMBRE_GESTORAField = value;
                this.RaisePropertyChanged("NOMBRE_GESTORA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal CODIGO_COOPERATIVA_CARGA {
            get {
                return this.cODIGO_COOPERATIVA_CARGAField;
            }
            set {
                this.cODIGO_COOPERATIVA_CARGAField = value;
                this.RaisePropertyChanged("CODIGO_COOPERATIVA_CARGA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NOMBRE_CARGA {
            get {
                return this.nOMBRE_CARGAField;
            }
            set {
                this.nOMBRE_CARGAField = value;
                this.RaisePropertyChanged("NOMBRE_CARGA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PTO_CARGA {
            get {
                return this.pTO_CARGAField;
            }
            set {
                this.pTO_CARGAField = value;
                this.RaisePropertyChanged("PTO_CARGA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string NOMBRE_PTO_CARGA {
            get {
                return this.nOMBRE_PTO_CARGAField;
            }
            set {
                this.nOMBRE_PTO_CARGAField = value;
                this.RaisePropertyChanged("NOMBRE_PTO_CARGA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NUMERO_SALIDA_COOPERATIVA {
            get {
                return this.nUMERO_SALIDA_COOPERATIVAField;
            }
            set {
                this.nUMERO_SALIDA_COOPERATIVAField = value;
                this.RaisePropertyChanged("NUMERO_SALIDA_COOPERATIVA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string N_LINEA_SALIDA_COOPERATIVA {
            get {
                return this.n_LINEA_SALIDA_COOPERATIVAField;
            }
            set {
                this.n_LINEA_SALIDA_COOPERATIVAField = value;
                this.RaisePropertyChanged("N_LINEA_SALIDA_COOPERATIVA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal N_PEDIDO_ANECOOP {
            get {
                return this.n_PEDIDO_ANECOOPField;
            }
            set {
                this.n_PEDIDO_ANECOOPField = value;
                this.RaisePropertyChanged("N_PEDIDO_ANECOOP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool N_PEDIDO_ANECOOPSpecified {
            get {
                return this.n_PEDIDO_ANECOOPFieldSpecified;
            }
            set {
                this.n_PEDIDO_ANECOOPFieldSpecified = value;
                this.RaisePropertyChanged("N_PEDIDO_ANECOOPSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal N_PEDIDO {
            get {
                return this.n_PEDIDOField;
            }
            set {
                this.n_PEDIDOField = value;
                this.RaisePropertyChanged("N_PEDIDO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool N_PEDIDOSpecified {
            get {
                return this.n_PEDIDOFieldSpecified;
            }
            set {
                this.n_PEDIDOFieldSpecified = value;
                this.RaisePropertyChanged("N_PEDIDOSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal N_LINEA {
            get {
                return this.n_LINEAField;
            }
            set {
                this.n_LINEAField = value;
                this.RaisePropertyChanged("N_LINEA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool N_LINEASpecified {
            get {
                return this.n_LINEAFieldSpecified;
            }
            set {
                this.n_LINEAFieldSpecified = value;
                this.RaisePropertyChanged("N_LINEASpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TIPO_EXPEDIENTE {
            get {
                return this.tIPO_EXPEDIENTEField;
            }
            set {
                this.tIPO_EXPEDIENTEField = value;
                this.RaisePropertyChanged("TIPO_EXPEDIENTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ESTADO_COOP_EXPEDIENTE {
            get {
                return this.eSTADO_COOP_EXPEDIENTEField;
            }
            set {
                this.eSTADO_COOP_EXPEDIENTEField = value;
                this.RaisePropertyChanged("ESTADO_COOP_EXPEDIENTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string EXPEDIENTE_REENVIADO {
            get {
                return this.eXPEDIENTE_REENVIADOField;
            }
            set {
                this.eXPEDIENTE_REENVIADOField = value;
                this.RaisePropertyChanged("EXPEDIENTE_REENVIADO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string CODIGO_DELEGACION {
            get {
                return this.cODIGO_DELEGACIONField;
            }
            set {
                this.cODIGO_DELEGACIONField = value;
                this.RaisePropertyChanged("CODIGO_DELEGACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string NOMBRE_DELEGACION {
            get {
                return this.nOMBRE_DELEGACIONField;
            }
            set {
                this.nOMBRE_DELEGACIONField = value;
                this.RaisePropertyChanged("NOMBRE_DELEGACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CODIGO_AREA {
            get {
                return this.cODIGO_AREAField;
            }
            set {
                this.cODIGO_AREAField = value;
                this.RaisePropertyChanged("CODIGO_AREA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string NOMBRE_AREA {
            get {
                return this.nOMBRE_AREAField;
            }
            set {
                this.nOMBRE_AREAField = value;
                this.RaisePropertyChanged("NOMBRE_AREA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.DateTime FECHA_SALIDA {
            get {
                return this.fECHA_SALIDAField;
            }
            set {
                this.fECHA_SALIDAField = value;
                this.RaisePropertyChanged("FECHA_SALIDA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_SALIDASpecified {
            get {
                return this.fECHA_SALIDAFieldSpecified;
            }
            set {
                this.fECHA_SALIDAFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_SALIDASpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string MATRICULA {
            get {
                return this.mATRICULAField;
            }
            set {
                this.mATRICULAField = value;
                this.RaisePropertyChanged("MATRICULA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string TIPO_VEHICULO {
            get {
                return this.tIPO_VEHICULOField;
            }
            set {
                this.tIPO_VEHICULOField = value;
                this.RaisePropertyChanged("TIPO_VEHICULO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string CATEGORIA {
            get {
                return this.cATEGORIAField;
            }
            set {
                this.cATEGORIAField = value;
                this.RaisePropertyChanged("CATEGORIA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string NOMBRE_CATEGORIA {
            get {
                return this.nOMBRE_CATEGORIAField;
            }
            set {
                this.nOMBRE_CATEGORIAField = value;
                this.RaisePropertyChanged("NOMBRE_CATEGORIA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CODIGO_CONFECCION {
            get {
                return this.cODIGO_CONFECCIONField;
            }
            set {
                this.cODIGO_CONFECCIONField = value;
                this.RaisePropertyChanged("CODIGO_CONFECCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string NOMBRE_CONFECCION {
            get {
                return this.nOMBRE_CONFECCIONField;
            }
            set {
                this.nOMBRE_CONFECCIONField = value;
                this.RaisePropertyChanged("NOMBRE_CONFECCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string CODIGO_UVENTA {
            get {
                return this.cODIGO_UVENTAField;
            }
            set {
                this.cODIGO_UVENTAField = value;
                this.RaisePropertyChanged("CODIGO_UVENTA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string NOMBRE_UVENTA {
            get {
                return this.nOMBRE_UVENTAField;
            }
            set {
                this.nOMBRE_UVENTAField = value;
                this.RaisePropertyChanged("NOMBRE_UVENTA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string CODIGO_ETRANSPORTE {
            get {
                return this.cODIGO_ETRANSPORTEField;
            }
            set {
                this.cODIGO_ETRANSPORTEField = value;
                this.RaisePropertyChanged("CODIGO_ETRANSPORTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string NOMBRE_ETRANSPORTE {
            get {
                return this.nOMBRE_ETRANSPORTEField;
            }
            set {
                this.nOMBRE_ETRANSPORTEField = value;
                this.RaisePropertyChanged("NOMBRE_ETRANSPORTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string CODIGO_MODELO {
            get {
                return this.cODIGO_MODELOField;
            }
            set {
                this.cODIGO_MODELOField = value;
                this.RaisePropertyChanged("CODIGO_MODELO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string NOMBRE_MODELO {
            get {
                return this.nOMBRE_MODELOField;
            }
            set {
                this.nOMBRE_MODELOField = value;
                this.RaisePropertyChanged("NOMBRE_MODELO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string CODIGO_MATERIAL {
            get {
                return this.cODIGO_MATERIALField;
            }
            set {
                this.cODIGO_MATERIALField = value;
                this.RaisePropertyChanged("CODIGO_MATERIAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string NOMBRE_MATERIAL {
            get {
                return this.nOMBRE_MATERIALField;
            }
            set {
                this.nOMBRE_MATERIALField = value;
                this.RaisePropertyChanged("NOMBRE_MATERIAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string CODIGO_MARCA {
            get {
                return this.cODIGO_MARCAField;
            }
            set {
                this.cODIGO_MARCAField = value;
                this.RaisePropertyChanged("CODIGO_MARCA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string NOMBRE_MARCA {
            get {
                return this.nOMBRE_MARCAField;
            }
            set {
                this.nOMBRE_MARCAField = value;
                this.RaisePropertyChanged("NOMBRE_MARCA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string CODIGO_VARIEDAD {
            get {
                return this.cODIGO_VARIEDADField;
            }
            set {
                this.cODIGO_VARIEDADField = value;
                this.RaisePropertyChanged("CODIGO_VARIEDAD");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string NOMBRE_VARIEDAD {
            get {
                return this.nOMBRE_VARIEDADField;
            }
            set {
                this.nOMBRE_VARIEDADField = value;
                this.RaisePropertyChanged("NOMBRE_VARIEDAD");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string CODIGO_ARTICULO {
            get {
                return this.cODIGO_ARTICULOField;
            }
            set {
                this.cODIGO_ARTICULOField = value;
                this.RaisePropertyChanged("CODIGO_ARTICULO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string NOMBRE_ARTICULO {
            get {
                return this.nOMBRE_ARTICULOField;
            }
            set {
                this.nOMBRE_ARTICULOField = value;
                this.RaisePropertyChanged("NOMBRE_ARTICULO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string CODIGO_CLIENTE {
            get {
                return this.cODIGO_CLIENTEField;
            }
            set {
                this.cODIGO_CLIENTEField = value;
                this.RaisePropertyChanged("CODIGO_CLIENTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string NOMBRECLIENTE {
            get {
                return this.nOMBRECLIENTEField;
            }
            set {
                this.nOMBRECLIENTEField = value;
                this.RaisePropertyChanged("NOMBRECLIENTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string CODIGO_PAIS {
            get {
                return this.cODIGO_PAISField;
            }
            set {
                this.cODIGO_PAISField = value;
                this.RaisePropertyChanged("CODIGO_PAIS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string CODIGO_DIVISA_CLIENTE {
            get {
                return this.cODIGO_DIVISA_CLIENTEField;
            }
            set {
                this.cODIGO_DIVISA_CLIENTEField = value;
                this.RaisePropertyChanged("CODIGO_DIVISA_CLIENTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string CODIGO_PRODUCTO {
            get {
                return this.cODIGO_PRODUCTOField;
            }
            set {
                this.cODIGO_PRODUCTOField = value;
                this.RaisePropertyChanged("CODIGO_PRODUCTO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string NOMBRE_PRODUCTO {
            get {
                return this.nOMBRE_PRODUCTOField;
            }
            set {
                this.nOMBRE_PRODUCTOField = value;
                this.RaisePropertyChanged("NOMBRE_PRODUCTO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string CODIGO_CALIBRE {
            get {
                return this.cODIGO_CALIBREField;
            }
            set {
                this.cODIGO_CALIBREField = value;
                this.RaisePropertyChanged("CODIGO_CALIBRE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string NOMBRE_CALIBRE {
            get {
                return this.nOMBRE_CALIBREField;
            }
            set {
                this.nOMBRE_CALIBREField = value;
                this.RaisePropertyChanged("NOMBRE_CALIBRE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public decimal NPALET {
            get {
                return this.nPALETField;
            }
            set {
                this.nPALETField = value;
                this.RaisePropertyChanged("NPALET");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string TIPO_PALET {
            get {
                return this.tIPO_PALETField;
            }
            set {
                this.tIPO_PALETField = value;
                this.RaisePropertyChanged("TIPO_PALET");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string NOMBRE_TIPO_PALET {
            get {
                return this.nOMBRE_TIPO_PALETField;
            }
            set {
                this.nOMBRE_TIPO_PALETField = value;
                this.RaisePropertyChanged("NOMBRE_TIPO_PALET");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public decimal NCAJAS {
            get {
                return this.nCAJASField;
            }
            set {
                this.nCAJASField = value;
                this.RaisePropertyChanged("NCAJAS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public decimal PESO_NETO {
            get {
                return this.pESO_NETOField;
            }
            set {
                this.pESO_NETOField = value;
                this.RaisePropertyChanged("PESO_NETO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public decimal PRECIO_COMERCIAL {
            get {
                return this.pRECIO_COMERCIALField;
            }
            set {
                this.pRECIO_COMERCIALField = value;
                this.RaisePropertyChanged("PRECIO_COMERCIAL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string CODIGO_DIVISA {
            get {
                return this.cODIGO_DIVISAField;
            }
            set {
                this.cODIGO_DIVISAField = value;
                this.RaisePropertyChanged("CODIGO_DIVISA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string LIQUIDADO_SON {
            get {
                return this.lIQUIDADO_SONField;
            }
            set {
                this.lIQUIDADO_SONField = value;
                this.RaisePropertyChanged("LIQUIDADO_SON");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string ESTADO_COOP_LIQUIDACION {
            get {
                return this.eSTADO_COOP_LIQUIDACIONField;
            }
            set {
                this.eSTADO_COOP_LIQUIDACIONField = value;
                this.RaisePropertyChanged("ESTADO_COOP_LIQUIDACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string LIQUIDACION_AGRUPADA_SON {
            get {
                return this.lIQUIDACION_AGRUPADA_SONField;
            }
            set {
                this.lIQUIDACION_AGRUPADA_SONField = value;
                this.RaisePropertyChanged("LIQUIDACION_AGRUPADA_SON");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string CODIGO_GRUPO_LIQUIDACION {
            get {
                return this.cODIGO_GRUPO_LIQUIDACIONField;
            }
            set {
                this.cODIGO_GRUPO_LIQUIDACIONField = value;
                this.RaisePropertyChanged("CODIGO_GRUPO_LIQUIDACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public decimal NUM_LIQ {
            get {
                return this.nUM_LIQField;
            }
            set {
                this.nUM_LIQField = value;
                this.RaisePropertyChanged("NUM_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUM_LIQSpecified {
            get {
                return this.nUM_LIQFieldSpecified;
            }
            set {
                this.nUM_LIQFieldSpecified = value;
                this.RaisePropertyChanged("NUM_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string FRA_LIQ {
            get {
                return this.fRA_LIQField;
            }
            set {
                this.fRA_LIQField = value;
                this.RaisePropertyChanged("FRA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string FRA_LIQ_COMPLEMENTA {
            get {
                return this.fRA_LIQ_COMPLEMENTAField;
            }
            set {
                this.fRA_LIQ_COMPLEMENTAField = value;
                this.RaisePropertyChanged("FRA_LIQ_COMPLEMENTA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string CARTA_LIQ {
            get {
                return this.cARTA_LIQField;
            }
            set {
                this.cARTA_LIQField = value;
                this.RaisePropertyChanged("CARTA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string REGISTRO_LIQ {
            get {
                return this.rEGISTRO_LIQField;
            }
            set {
                this.rEGISTRO_LIQField = value;
                this.RaisePropertyChanged("REGISTRO_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public decimal IMPORTE_LIQ {
            get {
                return this.iMPORTE_LIQField;
            }
            set {
                this.iMPORTE_LIQField = value;
                this.RaisePropertyChanged("IMPORTE_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IMPORTE_LIQSpecified {
            get {
                return this.iMPORTE_LIQFieldSpecified;
            }
            set {
                this.iMPORTE_LIQFieldSpecified = value;
                this.RaisePropertyChanged("IMPORTE_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public decimal IMPORTE_IVA_LIQ {
            get {
                return this.iMPORTE_IVA_LIQField;
            }
            set {
                this.iMPORTE_IVA_LIQField = value;
                this.RaisePropertyChanged("IMPORTE_IVA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IMPORTE_IVA_LIQSpecified {
            get {
                return this.iMPORTE_IVA_LIQFieldSpecified;
            }
            set {
                this.iMPORTE_IVA_LIQFieldSpecified = value;
                this.RaisePropertyChanged("IMPORTE_IVA_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public string TIPO_IVA_LIQ {
            get {
                return this.tIPO_IVA_LIQField;
            }
            set {
                this.tIPO_IVA_LIQField = value;
                this.RaisePropertyChanged("TIPO_IVA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public System.DateTime FECHA_LIQ {
            get {
                return this.fECHA_LIQField;
            }
            set {
                this.fECHA_LIQField = value;
                this.RaisePropertyChanged("FECHA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_LIQSpecified {
            get {
                return this.fECHA_LIQFieldSpecified;
            }
            set {
                this.fECHA_LIQFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public System.DateTime FECHA_CAMBIO_LIQ {
            get {
                return this.fECHA_CAMBIO_LIQField;
            }
            set {
                this.fECHA_CAMBIO_LIQField = value;
                this.RaisePropertyChanged("FECHA_CAMBIO_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_CAMBIO_LIQSpecified {
            get {
                return this.fECHA_CAMBIO_LIQFieldSpecified;
            }
            set {
                this.fECHA_CAMBIO_LIQFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_CAMBIO_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public decimal CAMBIO_LIQ {
            get {
                return this.cAMBIO_LIQField;
            }
            set {
                this.cAMBIO_LIQField = value;
                this.RaisePropertyChanged("CAMBIO_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CAMBIO_LIQSpecified {
            get {
                return this.cAMBIO_LIQFieldSpecified;
            }
            set {
                this.cAMBIO_LIQFieldSpecified = value;
                this.RaisePropertyChanged("CAMBIO_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public System.DateTime FECHA_SC_LIQ {
            get {
                return this.fECHA_SC_LIQField;
            }
            set {
                this.fECHA_SC_LIQField = value;
                this.RaisePropertyChanged("FECHA_SC_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_SC_LIQSpecified {
            get {
                return this.fECHA_SC_LIQFieldSpecified;
            }
            set {
                this.fECHA_SC_LIQFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_SC_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public decimal PORCENT_IVA_LIQ {
            get {
                return this.pORCENT_IVA_LIQField;
            }
            set {
                this.pORCENT_IVA_LIQField = value;
                this.RaisePropertyChanged("PORCENT_IVA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PORCENT_IVA_LIQSpecified {
            get {
                return this.pORCENT_IVA_LIQFieldSpecified;
            }
            set {
                this.pORCENT_IVA_LIQFieldSpecified = value;
                this.RaisePropertyChanged("PORCENT_IVA_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public decimal IMPORTE2_IVA_LIQ {
            get {
                return this.iMPORTE2_IVA_LIQField;
            }
            set {
                this.iMPORTE2_IVA_LIQField = value;
                this.RaisePropertyChanged("IMPORTE2_IVA_LIQ");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IMPORTE2_IVA_LIQSpecified {
            get {
                return this.iMPORTE2_IVA_LIQFieldSpecified;
            }
            set {
                this.iMPORTE2_IVA_LIQFieldSpecified = value;
                this.RaisePropertyChanged("IMPORTE2_IVA_LIQSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public string COBRADO_SON {
            get {
                return this.cOBRADO_SONField;
            }
            set {
                this.cOBRADO_SONField = value;
                this.RaisePropertyChanged("COBRADO_SON");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public string PAGADO_SON {
            get {
                return this.pAGADO_SONField;
            }
            set {
                this.pAGADO_SONField = value;
                this.RaisePropertyChanged("PAGADO_SON");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public decimal VALOR_MERCANCIA {
            get {
                return this.vALOR_MERCANCIAField;
            }
            set {
                this.vALOR_MERCANCIAField = value;
                this.RaisePropertyChanged("VALOR_MERCANCIA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR_MERCANCIASpecified {
            get {
                return this.vALOR_MERCANCIAFieldSpecified;
            }
            set {
                this.vALOR_MERCANCIAFieldSpecified = value;
                this.RaisePropertyChanged("VALOR_MERCANCIASpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=80)]
        public decimal VALOR_CONFECCION {
            get {
                return this.vALOR_CONFECCIONField;
            }
            set {
                this.vALOR_CONFECCIONField = value;
                this.RaisePropertyChanged("VALOR_CONFECCION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VALOR_CONFECCIONSpecified {
            get {
                return this.vALOR_CONFECCIONFieldSpecified;
            }
            set {
                this.vALOR_CONFECCIONFieldSpecified = value;
                this.RaisePropertyChanged("VALOR_CONFECCIONSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=81)]
        public decimal NUMERO_SALIDA_ANECOOP {
            get {
                return this.nUMERO_SALIDA_ANECOOPField;
            }
            set {
                this.nUMERO_SALIDA_ANECOOPField = value;
                this.RaisePropertyChanged("NUMERO_SALIDA_ANECOOP");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NUMERO_SALIDA_ANECOOPSpecified {
            get {
                return this.nUMERO_SALIDA_ANECOOPFieldSpecified;
            }
            set {
                this.nUMERO_SALIDA_ANECOOPFieldSpecified = value;
                this.RaisePropertyChanged("NUMERO_SALIDA_ANECOOPSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=82)]
        public string SALIDALINEAID {
            get {
                return this.sALIDALINEAIDField;
            }
            set {
                this.sALIDALINEAIDField = value;
                this.RaisePropertyChanged("SALIDALINEAID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public string CODIGO_TIPO_ARTICULO {
            get {
                return this.cODIGO_TIPO_ARTICULOField;
            }
            set {
                this.cODIGO_TIPO_ARTICULOField = value;
                this.RaisePropertyChanged("CODIGO_TIPO_ARTICULO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=84)]
        public string EAN13 {
            get {
                return this.eAN13Field;
            }
            set {
                this.eAN13Field = value;
                this.RaisePropertyChanged("EAN13");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=85)]
        public string UNIDAD_PESO {
            get {
                return this.uNIDAD_PESOField;
            }
            set {
                this.uNIDAD_PESOField = value;
                this.RaisePropertyChanged("UNIDAD_PESO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("EXPEDIENTE_PAGO", Order=86)]
        public DescargaPedidosResultExpedienteEXPEDIENTE_PAGO[] EXPEDIENTE_PAGO {
            get {
                return this.eXPEDIENTE_PAGOField;
            }
            set {
                this.eXPEDIENTE_PAGOField = value;
                this.RaisePropertyChanged("EXPEDIENTE_PAGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("EXPEDIENTE_COBRO", Order=87)]
        public DescargaPedidosResultExpedienteEXPEDIENTE_COBRO[] EXPEDIENTE_COBRO {
            get {
                return this.eXPEDIENTE_COBROField;
            }
            set {
                this.eXPEDIENTE_COBROField = value;
                this.RaisePropertyChanged("EXPEDIENTE_COBRO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DescargaPedidosResultExpedienteEXPEDIENTE_PAGO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eXPEDIENTE_PAGOIDField;
        
        private string eXPEDIENTE_IDField;
        
        private string tIPO_PAGOField;
        
        private string nUM_FACTURAField;
        
        private System.DateTime fECHA_FACTURAField;
        
        private bool fECHA_FACTURAFieldSpecified;
        
        private string nUM_LIQUIDACIONField;
        
        private decimal iMPORTEField;
        
        private System.DateTime fECHA_PAGOField;
        
        private bool fECHA_PAGOFieldSpecified;
        
        private System.DateTime fECHA_PAGO_SCField;
        
        private bool fECHA_PAGO_SCFieldSpecified;
        
        private string eSTADOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EXPEDIENTE_PAGOID {
            get {
                return this.eXPEDIENTE_PAGOIDField;
            }
            set {
                this.eXPEDIENTE_PAGOIDField = value;
                this.RaisePropertyChanged("EXPEDIENTE_PAGOID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EXPEDIENTE_ID {
            get {
                return this.eXPEDIENTE_IDField;
            }
            set {
                this.eXPEDIENTE_IDField = value;
                this.RaisePropertyChanged("EXPEDIENTE_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TIPO_PAGO {
            get {
                return this.tIPO_PAGOField;
            }
            set {
                this.tIPO_PAGOField = value;
                this.RaisePropertyChanged("TIPO_PAGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NUM_FACTURA {
            get {
                return this.nUM_FACTURAField;
            }
            set {
                this.nUM_FACTURAField = value;
                this.RaisePropertyChanged("NUM_FACTURA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime FECHA_FACTURA {
            get {
                return this.fECHA_FACTURAField;
            }
            set {
                this.fECHA_FACTURAField = value;
                this.RaisePropertyChanged("FECHA_FACTURA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_FACTURASpecified {
            get {
                return this.fECHA_FACTURAFieldSpecified;
            }
            set {
                this.fECHA_FACTURAFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_FACTURASpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NUM_LIQUIDACION {
            get {
                return this.nUM_LIQUIDACIONField;
            }
            set {
                this.nUM_LIQUIDACIONField = value;
                this.RaisePropertyChanged("NUM_LIQUIDACION");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal IMPORTE {
            get {
                return this.iMPORTEField;
            }
            set {
                this.iMPORTEField = value;
                this.RaisePropertyChanged("IMPORTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime FECHA_PAGO {
            get {
                return this.fECHA_PAGOField;
            }
            set {
                this.fECHA_PAGOField = value;
                this.RaisePropertyChanged("FECHA_PAGO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_PAGOSpecified {
            get {
                return this.fECHA_PAGOFieldSpecified;
            }
            set {
                this.fECHA_PAGOFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_PAGOSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime FECHA_PAGO_SC {
            get {
                return this.fECHA_PAGO_SCField;
            }
            set {
                this.fECHA_PAGO_SCField = value;
                this.RaisePropertyChanged("FECHA_PAGO_SC");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FECHA_PAGO_SCSpecified {
            get {
                return this.fECHA_PAGO_SCFieldSpecified;
            }
            set {
                this.fECHA_PAGO_SCFieldSpecified = value;
                this.RaisePropertyChanged("FECHA_PAGO_SCSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DescargaPedidosResultExpedienteEXPEDIENTE_COBRO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eXPEDIENTE_COBROIDField;
        
        private string eXPEDIENTE_IDField;
        
        private string nUMERO_REMESAField;
        
        private decimal iMPORTE_CAMBIOField;
        
        private System.DateTime fECHA_CAMBIOField;
        
        private string eSTADOField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EXPEDIENTE_COBROID {
            get {
                return this.eXPEDIENTE_COBROIDField;
            }
            set {
                this.eXPEDIENTE_COBROIDField = value;
                this.RaisePropertyChanged("EXPEDIENTE_COBROID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EXPEDIENTE_ID {
            get {
                return this.eXPEDIENTE_IDField;
            }
            set {
                this.eXPEDIENTE_IDField = value;
                this.RaisePropertyChanged("EXPEDIENTE_ID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NUMERO_REMESA {
            get {
                return this.nUMERO_REMESAField;
            }
            set {
                this.nUMERO_REMESAField = value;
                this.RaisePropertyChanged("NUMERO_REMESA");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal IMPORTE_CAMBIO {
            get {
                return this.iMPORTE_CAMBIOField;
            }
            set {
                this.iMPORTE_CAMBIOField = value;
                this.RaisePropertyChanged("IMPORTE_CAMBIO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime FECHA_CAMBIO {
            get {
                return this.fECHA_CAMBIOField;
            }
            set {
                this.fECHA_CAMBIOField = value;
                this.RaisePropertyChanged("FECHA_CAMBIO");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DescargaPedidos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DescargaPedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuarioCodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sessionKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string salidaCoopNumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string expedienteID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string numeroFactura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaFacturaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaFacturaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string codigoCampanya;
        
        public DescargaPedidosRequest() {
        }
        
        public DescargaPedidosRequest(string usuarioCodigo, string sessionKey, System.Nullable<System.DateTime> fechaInicio, System.Nullable<System.DateTime> fechaFin, string salidaCoopNumero, string expedienteID, string estado, string numeroFactura, System.Nullable<System.DateTime> fechaFacturaInicio, System.Nullable<System.DateTime> fechaFacturaFin, string codigoCampanya) {
            this.usuarioCodigo = usuarioCodigo;
            this.sessionKey = sessionKey;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.salidaCoopNumero = salidaCoopNumero;
            this.expedienteID = expedienteID;
            this.estado = estado;
            this.numeroFactura = numeroFactura;
            this.fechaFacturaInicio = fechaFacturaInicio;
            this.fechaFacturaFin = fechaFacturaFin;
            this.codigoCampanya = codigoCampanya;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DescargaPedidosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DescargaPedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Expediente", IsNullable=false)]
        public ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResultExpediente[] DescargaPedidosResult;
        
        public DescargaPedidosResponse() {
        }
        
        public DescargaPedidosResponse(ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResultExpediente[] DescargaPedidosResult) {
            this.DescargaPedidosResult = DescargaPedidosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JSVConsultaExpedienteSoapChannel : ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JSVConsultaExpedienteSoapClient : System.ServiceModel.ClientBase<ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap>, ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap {
        
        public JSVConsultaExpedienteSoapClient() {
        }
        
        public JSVConsultaExpedienteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JSVConsultaExpedienteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JSVConsultaExpedienteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JSVConsultaExpedienteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResponse ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap.DescargaPedidos(ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest request) {
            return base.Channel.DescargaPedidos(request);
        }
        
        public ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResultExpediente[] DescargaPedidos(string usuarioCodigo, string sessionKey, System.Nullable<System.DateTime> fechaInicio, System.Nullable<System.DateTime> fechaFin, string salidaCoopNumero, string expedienteID, string estado, string numeroFactura, System.Nullable<System.DateTime> fechaFacturaInicio, System.Nullable<System.DateTime> fechaFacturaFin, string codigoCampanya) {
            ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest inValue = new ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest();
            inValue.usuarioCodigo = usuarioCodigo;
            inValue.sessionKey = sessionKey;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.salidaCoopNumero = salidaCoopNumero;
            inValue.expedienteID = expedienteID;
            inValue.estado = estado;
            inValue.numeroFactura = numeroFactura;
            inValue.fechaFacturaInicio = fechaFacturaInicio;
            inValue.fechaFacturaFin = fechaFacturaFin;
            inValue.codigoCampanya = codigoCampanya;
            ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResponse retVal = ((ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap)(this)).DescargaPedidos(inValue);
            return retVal.DescargaPedidosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResponse> ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap.DescargaPedidosAsync(ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest request) {
            return base.Channel.DescargaPedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosResponse> DescargaPedidosAsync(string usuarioCodigo, string sessionKey, System.Nullable<System.DateTime> fechaInicio, System.Nullable<System.DateTime> fechaFin, string salidaCoopNumero, string expedienteID, string estado, string numeroFactura, System.Nullable<System.DateTime> fechaFacturaInicio, System.Nullable<System.DateTime> fechaFacturaFin, string codigoCampanya) {
            ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest inValue = new ConAnecoop.AnecoopConsultaExpediente.DescargaPedidosRequest();
            inValue.usuarioCodigo = usuarioCodigo;
            inValue.sessionKey = sessionKey;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.salidaCoopNumero = salidaCoopNumero;
            inValue.expedienteID = expedienteID;
            inValue.estado = estado;
            inValue.numeroFactura = numeroFactura;
            inValue.fechaFacturaInicio = fechaFacturaInicio;
            inValue.fechaFacturaFin = fechaFacturaFin;
            inValue.codigoCampanya = codigoCampanya;
            return ((ConAnecoop.AnecoopConsultaExpediente.JSVConsultaExpedienteSoap)(this)).DescargaPedidosAsync(inValue);
        }
    }
}
